### PR TITLE
Keep preproc inside the tidyverse

### PR DESCRIPTION
**Pull request by benwhalley**
Removes looping when importing multiple files as discussed.

Also converted to `set_names()` rather than `names(df) <- x` because again avoids mutating in place... could skip those changes if you want and sorry there are not in a separate PR.

Finally, added a simple example of using `str_extract` with `\\d+` to get participants IDs. This works better if you have > 99 participants (or use p1..p9 etc).

### CODE REVIEW

**Review by ajwills72 — COMMENTED** [review]
Hey Ben
I like what you've done here, but I think it needs a wee bit of polishing before I merge into master. Notes below.
Best
Andy

src/preproc.Rmd

Line 150 changes 'tidydat' to 'dat_subset', which will cause problems
with at least line 164 (renaming columns) and possibly several future commands in the worksheet (which still use 'tidydat')

Line 259 - typo "if didn't do this"

Line 284 - Code for exercise now uses a syntax that will not be familiar to students (using subj=filename in group_by), which means they probably won't be able to reproduce the output as shown. Perhaps use just `group_by(filename, type)` instead?

Line 308 - Same issue (which you note in comments). The exercise uses code that is not familiar to the students. This is not great for a number of reasons - reproducibility of output from student perspective (as discussed above) but also because instructors (and the auto-mark system in Psyc:EL) use this hidden-to-students code as a model answer. Please could you fix hidden code to use same syntax as taught?

src/more-on-preproc.Rmd

Line 24,  59 - I reckon `.before=TRUE` is clearer (yup, I know it's logically equivalent, but the students don't). 

Line 36 - 'vector' is not a term that is used anywhere else in RMINR and so will be unfamiliar to the reader. Please avoid (or, if you really feel you need to, define it I guess).

Link 77 - Seems like an exericse? If so, please identify as such with a sub-heading, as normal. Alternatively, drop. 

Finally - please add yourself to the author list of both pages.

**Comment by benwhalley** [comment]
I'm hoping I've done this right... I think my new commits have been added to the previous PR.

Sorry to have wasted your time before also... I’m not sure how, but I had managed to mangle the commit by having two copies of the repo locally and not realising. Ugh.

Anyway - on your comments:


> src/preproc.Rmd
> 
> Line 150 changes 'tidydat' to 'dat_subset', which will cause problems
> with at least line 164 (renaming columns) and possibly several future commands in the worksheet (which still use 'tidydat')
> 

Yes - this is now fixed by creating `tidydat` on line 164 when renaming the columns. Inn adding the extra step I was trying to avoid over-writing existing variable names because that introduces dependencies in code execution which don’t always fail but are a common source of problems/confusion.



> Line 259 - typo "if didn't do this"

Fixed

> 
> Line 284 - Code for exercise now uses a syntax that will not be familiar to students (using subj=filename in group_by), which means they probably won't be able to reproduce the output as shown. Perhaps use just group_by(filename, type) instead?

Fixed


> Line 308 - Same issue (which you note in comments). The exercise uses code that is not familiar to the students. This is not great for a number of reasons - reproducibility of output from student perspective (as discussed above) but also because instructors (and the auto-mark system in Psyc:EL) use this hidden-to-students code as a model answer. Please could you fix hidden code to use same syntax as taught?

Made consistent. Will have to get you to show me the automark thing sometime. Is it just a 1:1 match or more clever than that?

> 
> src/more-on-preproc.Rmd
> 
> Line 24, 59 - I reckon .before=TRUE is clearer (yup, I know it's logically equivalent, but the students don't).

I switched this because in when using .before=T with mutate (rather than add_column) I get this error:

```
Error: Must subset columns with a valid subscript vector. x Subscript has the wrong type `logical`. ℹ It must be numeric or character.
```

I think  `.before=T`  may only work with add_column because `as.numeric(TRUE) == 1` and it’s coercing it somewhere. 

The help file for `add_column` says it expects a "One-based column index or column name”. My feeling is that it would be better to show syntax that works with both `mutate` and `add_column`, and `.before=T` working is maybe a bug not a feature… I can’t imagine them relaxing the signature to allow booleans too because it’s less explicit.

Would it be clearer to students to say `.before=“colname”` rather than giving the index? My guess was "probably yes", so have switched to using that in this commit, but feel free to switch back to TRUE for the add_column calls if you prefer (but remember it won’t work for the mutate on line 59). I have also searched the rminr source and this is the only place .before= is used so it should be consistent.

> 
> Line 36 - 'vector' is not a term that is used anywhere else in RMINR and so will be unfamiliar to the reader. Please avoid (or, if you really feel you need to, define it I guess).

Good spot — have switched back to “list”.

In doing a find and replace I spotted that Paul’s ‘more-on-data.Rmd’ also uses vector and I’ve made a small amend to that file (to use the word “list” instead and added a note in parentheses).

Funnily enough, that file also uses map_df to import multiple Excel sheets which I hadn’t spotted before. It’s probably fine this way: The use-case there is different enough to warrant using do when importing multiple files and map_df to handle the multiple data frames which get created when importing multi-sheet xlsx.


> 
> Link 77 - Seems like an exericse? If so, please identify as such with a sub-heading, as normal. Alternatively, drop.

Created section

> 
> Finally - please add yourself to the author list of both pages.
> 

Done.

**Review by ajwills72 — COMMENTED** [review]
Getting very close :-) The term 'vector' is still used in more-on-preproc.Rmd, line 36. I haven't looked closely as changes to more-on-data.Rmd, as this is currently an orhpan page (i.e. exists in the repo, but is not linked from anywhere, so invisible to end user. I think it's a page Paul started but did not finish.

Suggestion for future changes beyond these: Rather than a PR, perhaps make a branch for your change -- we could then work more collaboratively on that branch, which might be more efficient than the github-comment-on-PR workflow, which personally I find a bit clunky.

**Comment by ajwills72** [comment]
Now implemented, although outside of this pull request.

**Pull request closed without merging**
