### PR TITLE
Fix cohen.d() output explanation

### PR DESCRIPTION
**Pull request by earcanal**
* Looks like it doesn't use `inf` and `sup` any more

### CODE REVIEW

**Comment by earcanal** [comment]
Revert commit that also pushed `src/fig1.pdf` and retry.

**Review by ajwills72 — CHANGES_REQUESTED** [review]
You've put two qualitatively different changes into the same pull request. This causes me an issue, as I'm happy to merge one (concern effect size) but not the other (concerning Bayes - for which the wording, as you say, needs some work). Please submit separate PRs for each issue.

**Comment by earcanal** [comment]
Duh. I hoped that last commit wouldn't be automatically added to the PR.

Could you just `cherry-pick` 5611f3b0d0c4e57130ecde219a31ffb1e5de5603 and do the Bayes wording on a different branch?

**Review by ajwills72 — APPROVED** [review]
Hopefully selectively approving the effect size commit...

**Comment by ajwills72** [comment]
Nope, that doesn't work. Closing pull request. Will do effect size change manually. Submit BF change as new PR if you wish.

**Pull request closed without merging**
